active_stack_id: a43c96b6-9253-4464-b8a3-72af1fee3ec2
active_workspace_name: default
analytics_opt_in: true
store:
  api_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNWMyZWI3ZS0zMzNkLTQ2YWYtYWQ5Yi1mZDAyMmQ0OTZjOTEiLCJpc3MiOiI3NjVjNzExYy0yNWY4LTQ2N2UtYWY0Ny1mNmU2YjI1YmE5YzMiLCJhdWQiOiI3NjVjNzExYy0yNWY4LTQ2N2UtYWY0Ny1mNmU2YjI1YmE5YzMifQ.hYMg55vuiaJ4aM1mptq3ceAx0hw9aVjEeM7Ri3Y0_rE
  http_timeout: 30
  password: ''
  type: rest
  url: http://127.0.0.1:8237
  username: default
  verify_ssl: true
user_id: 765c711c-25f8-467e-af47-f6e6b25ba9c3
version: 0.58.2
