active_stack_id: 8d8cb8e1-06a6-4a50-aaf2-975846651f0c
active_workspace_name: default
analytics_opt_in: true
store:
  api_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YWUxMDk5MC1iODEyLTQ1YTUtOWIxZS1hNGMwYzNiNTRlNWIiLCJpc3MiOiI4ZjJhOWJhMy1lMmFkLTRmMjEtYjdlYS01MjU3ZDA1OTM5YmUiLCJhdWQiOiI4ZjJhOWJhMy1lMmFkLTRmMjEtYjdlYS01MjU3ZDA1OTM5YmUifQ.frtDGUtsPb4XSDoX9Kb7BD0sWk8fNWJm6314Qr_jjKo
  http_timeout: 30
  password: ''
  type: rest
  url: http://127.0.0.1:8237
  username: default
  verify_ssl: true
user_id: 8f2a9ba3-e2ad-4f21-b7ea-5257d05939be
version: 0.58.2
