params: {
  'hidden_dim': [ 512 ],
  'hidden_layers': [ 3 ],
  'batch_size': [ 128 ],
  # hyperparameters to search
  'lr': [ 0.0001, 0.001, 0.01 ],
  'epochs': [ 10, 50, 100, 200 ],
  'optimizer': [ 'SGD','Adam','RMSprop']
}