params: {
  'hidden_dim': [ 512 ],
  'hidden_layers': [ 3 ],
  'batch_size': [ 64 ],
  # hyperparameters to search
  'lr': [ 0.0001, 0.001, 0.01 ],
  'epochs': [ 40, 50, 100 ],
  'optimizer': [ 'SGD','Adam','RMSprop']
}